// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RoboSphere.Discord.Data;

namespace RoboSphere.Discord.Migrations
{
    [DbContext(typeof(SqlContext))]
    internal class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("RoboSphere.Discord.Data.Models.Setting", b =>
            {
                b.Property<int>("SettingId").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                b.Property<string>("Key").IsRequired().HasMaxLength(128).HasColumnType("TEXT");

                b.Property<string>("Value").IsRequired().HasColumnType("TEXT");

                b.HasKey("SettingId");

                b.HasIndex("Key");

                b.ToTable("Settings");
            });

            modelBuilder.Entity("RoboSphere.Discord.Data.Models.Stopwatch", b =>
            {
                b.Property<int>("StopwatchId").ValueGeneratedOnAdd().HasColumnType("INTEGER");

                b.Property<string>("Key").IsRequired().HasMaxLength(128).HasColumnType("TEXT");

                b.Property<long>("Next").HasColumnType("INTEGER");

                b.HasKey("StopwatchId");

                b.HasIndex("Key");

                b.ToTable("Stopwatch");
            });
#pragma warning restore 612, 618
        }
    }
}
